axis_linear: 1  # Left thumb stick vertical
scale_linear: 1.5
scale_linear_turbo: 1.5

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 3

enable_button: 2  # 2 == X trigger button
enable_turbo_button: -1  # Disabled
